receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  file:
    path: /etc/otelcol-contrib/data-otlp.json
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
