name: CLI Test

on:
  push:
    branches: [master, 'release/**']
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [master, 'release/**']
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: linux_apisix_current_luarocks
      OPENRESTY_VERSION: default

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache deps
        uses: actions/cache@v4
        env:
          cache-name: cache-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.cache-name }}-linux_apisix_current_luarocks-${{ hashFiles('apisix-master-0.rockspec') }}

      - name: Linux launch common services
        run: |
          project_compose_ci=ci/pod/docker-compose.common.yml make ci-env-up

      - name: Linux Before install
        run: sudo ./ci/linux_apisix_current_luarocks_runner.sh before_install

      - name: Linux Install
        run: |
          sudo --preserve-env=OPENRESTY_VERSION \
          ./ci/linux_apisix_current_luarocks_runner.sh do_install
          # Fix permissions after install
          sudo chmod -R a+rX "$GITHUB_WORKSPACE"

      - name: Linux Script
        run: |
          sudo chmod +x /home/runner
          sudo sh -c 'umask 022 && ./ci/linux_apisix_current_luarocks_runner.sh script'
